# Generated by Django 3.2.9 on 2021-12-04 22:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='movieTitle', max_length=50)),
                ('date', models.DateField(db_column='movieDate')),
                ('desc', models.CharField(db_column='movieDescription', max_length=400)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), db_column='movieGenres', size=None)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
