# Generated by Django 3.2.9 on 2021-12-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesAPP', '0002_movie_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField(db_column='roomSeatsQuantity')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
