# Generated by Django 3.2.9 on 2021-12-04 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesAPP', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='roomID',
            field=models.OneToOneField(db_column='movieRoomID', null=True, on_delete=django.db.models.deletion.CASCADE, to='MoviesAPP.room'),
        ),
    ]
