# Generated by Django 3.2.9 on 2021-12-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesAPP', '0004_movie_roomid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(db_column='movieID', primary_key=True, serialize=False),
        ),
    ]
