# Generated by Django 3.2.9 on 2021-12-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesAPP', '0006_alter_movie_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='roomID',
            field=models.ForeignKey(db_column='movieRoomID', null=True, on_delete=django.db.models.deletion.CASCADE, to='MoviesAPP.room'),
        ),
    ]
