# Generated by Django 3.2.9 on 2021-12-05 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(db_column='employeeID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('position', models.CharField(db_column='employeePosition', max_length=50)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
